### ISSUE TITLE
Would you please provide a GPU friendly batched parallel execution 

### ISSUE THREAD

**Issue by jianqingzhu** [JDEA-Quantum-Lab/TeD-Q#3]
Thanks for providing a nice work.  Now, I find that in QNN demo, pythorch forward, batch samples are handled one by one in a for loop,  which is unfriendly for GPU. I look forward to a faster version of parallel execution. Thanks.

**Comment by yaochengchen** [comment]
Thank you for your comment. If you are using PyTorch backend, you can install functorch, and then use the vmap function for batch execution. Some modification is done on develop branch for fulfilling vamp's requirements and Quantum_transfer_learning_original_circuit.ipynb DressedQuantumNet class is also updated as usage reference.

You need to install functorch as below for PyTorch 1.12.0 cu102 binary
pip install --user git+https://github.com/pytorch/functorch@v0.2.0
https://pytorch.org/functorch/stable/install.html

For small batch size and small qubits, maybe CPU is faster than GPU. If the input data of quantum function are all in GPU, then TeD-Q will run on GPU, otherwise it will use CPU.
